# Generated by Django 5.2.9 on 2025-12-09 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='OptimizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=1, help_text='Wyższy numer = ważniejsza reguła')),
                ('is_active', models.BooleanField(default=True)),
                ('condition', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(blank=True, help_text='Np. docelowa temperatura lub jasność', null=True)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='simulation.device')),
            ],
        ),
    ]
