# Generated by Django 5.2.9 on 2025-12-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Komentarz alarmu',
                'verbose_name_plural': 'Komentarze alarmów',
                'db_table': 'alert_comment',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('operator', models.CharField(choices=[('GREATER_THAN', 'Większe niż'), ('LESS_THAN', 'Mniejsze niż'), ('EQUALS', 'Równe')], max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_metric', models.CharField(max_length=255)),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Krytyczny'), ('HIGH', 'Wysoki'), ('MEDIUM', 'Średni'), ('LOW', 'Niski')], default='MEDIUM', max_length=20)),
            ],
            options={
                'verbose_name': 'Reguła alarmu',
                'verbose_name_plural': 'Reguły alarmów',
                'db_table': 'alert_rule',
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WEBPUSH', 'WebPush')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Typ kanału',
                'verbose_name_plural': 'Typy kanałów',
                'db_table': 'channel_type',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggering_value', models.FloatField()),
                ('timestamp_generated', models.DateTimeField(auto_now_add=True)),
                ('timestamp_acknowledged', models.DateTimeField(blank=True, null=True)),
                ('timestamp_closed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nowy'), ('ACKNOWLEDGED', 'Potwierdzony'), ('CLOSED', 'Zamknięty')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Krytyczny'), ('HIGH', 'Wysoki'), ('MEDIUM', 'Średni'), ('LOW', 'Niski')], default='MEDIUM', max_length=20)),
                ('alert_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alarms.alertcomment')),
                ('alert_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alarms.alertrule')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarmy',
                'db_table': 'alert',
                'ordering': ['-timestamp_generated'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(related_name='notification_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupa powiadomień',
                'verbose_name_plural': 'Grupy powiadomień',
                'db_table': 'notification_group',
            },
        ),
        migrations.CreateModel(
            name='SZEBiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='szebi_users', to='alarms.notificationgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='szebi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Użytkownik SZEBi',
                'verbose_name_plural': 'Użytkownicy SZEBi',
                'db_table': 'szebi_user',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_webpush', models.BooleanField(default=True)),
                ('min_priority_level', models.CharField(choices=[('CRITICAL', 'Krytyczny'), ('HIGH', 'Wysoki'), ('MEDIUM', 'Średni'), ('LOW', 'Niski')], default='LOW', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='alarms.szebiuser')),
            ],
            options={
                'verbose_name': 'Preferencja powiadomień',
                'verbose_name_plural': 'Preferencje powiadomień',
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Wysłane'), ('FAILED', 'Nieudane')], default='SENT', max_length=20)),
                ('timestamp_sent', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alarms.alert')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarms.channeltype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='alarms.szebiuser')),
            ],
            options={
                'verbose_name': 'Log powiadomień',
                'verbose_name_plural': 'Logi powiadomień',
                'db_table': 'notification_log',
                'ordering': ['-timestamp_sent'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='alarms.szebiuser'),
        ),
        migrations.AddField(
            model_name='alert',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_alerts', to='alarms.szebiuser'),
        ),
    ]
