# Generated by Django 5.2.8 on 2025-12-02 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('CONSUMER', 'Odbiornik (np. HVAC, Oświetlenie)'), ('PRODUCER', 'Producent (np. Fotowoltaika)'), ('STORAGE', 'Magazyn Energii')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('nominal_power', models.FloatField(help_text='Moc w kW (dodatnia)')),
                ('priority', models.IntegerField(default=1, help_text='1 = krytyczne, 10 = można wyłączyć')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_kwh', models.DecimalField(decimal_places=4, max_digits=6)),
                ('start_hour', models.IntegerField(default=0)),
                ('end_hour', models.IntegerField(default=23)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sim_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('cloud_cover', models.FloatField(help_text='0-100%')),
                ('wind_speed', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
