# Generated by Django 6.0 on 2025-12-09 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(db_column='type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_unit', models.CharField(max_length=20)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='location_id', primary_key=True, serialize=False)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['room'], name='acquisition_room_62ea72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(db_column='sensor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('FAILED', 'Failed')], default='ACTIVE', max_length=15)),
                ('installation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acquisition.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acquisition.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(db_column='measurement_id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicate'), ('NULL', 'Null')], default='OK', max_length=15)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acquisition.sensor')),
            ],
            options={
                'unique_together': {('sensor', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acquisition.measurement')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='acquisition_timesta_13f1e3_idx'), models.Index(fields=['level'], name='acquisition_level_5155cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['status'], name='acquisition_status_6cfe22_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['last_communication'], name='acquisition_last_co_e84581_idx'),
        ),
    ]
